"""add pokedata_url to search_queries

Revision ID: 45d300e107b8
Revises: a1c4d9b2e7f3
Create Date: 2026-05-11 16:09:39.740302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d300e107b8'
down_revision: Union[str, Sequence[str], None] = 'a1c4d9b2e7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_queries', sa.Column('pokedata_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_queries', 'pokedata_url')
    # ### end Alembic commands ###
