"""add manual_market_price to search_queries

Revision ID: 69bc2620316a
Revises: a3b9498f763e
Create Date: 2026-05-11 17:57:02.087294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bc2620316a'
down_revision: Union[str, Sequence[str], None] = 'a3b9498f763e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_queries', sa.Column('manual_market_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_queries', 'manual_market_price')
    # ### end Alembic commands ###
