"""Add hide_above_market column

Revision ID: 9d2f457b49d3
Revises: 69bc2620316a
Create Date: 2026-05-11 18:34:51.031622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2f457b49d3'
down_revision: Union[str, Sequence[str], None] = '69bc2620316a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_queries', sa.Column('hide_above_market', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_queries', 'hide_above_market')
    # ### end Alembic commands ###
